name: Plugin compatibility
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8.x.x
    - name: Build the plugin using Gradle
      run: ./gradlew buildPlugin
    - uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
      with:
        ide-versions: |
          ideaIC:193.5662.53
          ideaIU:193.5662.53
